services:
  postgres:
    image: postgres:17.7-trixie
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - path: ./go.env
        required: true
volumes:
  postgres_data:
